name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip meson ninja
      - run: |
          meson setup --vsenv --buildtype=release -Dtests=enabled builddir
          meson dist -C builddir

  docs:
    needs:
      - lint
      - test
    concurrency:
      group: publish-gh-pages
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip meson ninja
      - run: |
          sudo apt-get install -y doxygen
      - run: |
          meson setup -Ddocs=enabled builddir
          meson compile -C builddir docs
      - run: |
          cd builddir
          mkdir alldocs
          mv OpenScanLib/doc/apidoc/html alldocs/OpenScanLib
          mv OpenScanDeviceLib/doc/apidoc/html alldocs/OpenScanDeviceLib
          cat >alldocs/index.html <<EOF
          <!DOCTYPE html>
          <html><head><title>OpenScanLib Documentation</title></head><body>
          <a href="OpenScanLib/">OpenScanLib API Documentation</a><br />
          <a href="OpenScanDeviceLib/">OpenScanDeviceLib Documentation</a>
          </body></html>
          EOF
      - if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: builddir/alldocs
